base_local_planner: "base_local_planner/TrajectoryPlannerROS"
planner_frequency: 0.1
max_planning_retries: 3

TrajectoryPlannerROS:
  # realmax 0.43,2
  max_vel_x: 0.65 #WHEEL_RADIUS*V_MAX = 0.65 m/s
  min_vel_x: -0.1 
  max_vel_theta: 0.5 #(max_vel_x+max_vel_x)/WHEEL_SEPARATION =6.43 rad/s
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0
  escape_vel: -0.1

  acc_lim_theta: 3.2
  acc_lim_x: 2.5

  holonomic_robot: false
  #Use default value
  # goal_distance_bias: 60 
  # path_distance_bias: 5
  # occdist_scale: 0.01


  xy_goal_tolerance: 0.01
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true
  meter_scoring: true

  sim_time: 1.5
  controller_frequency: 20.0
  sim_granularity: 0.05
  angular_sim_granularity: 0.025
  vx_samples: 20
  vth_samples: 20
  vy_samples: 10
  

