planner_frequency: 0.25
controller_frequency: 20.0
max_planning_retries: 1

DWAPlannerROS:
  # realmax 0.43,2
  max_vel_x: 1
  min_vel_x: -1  
  max_vel_theta: 3
  min_vel_theta: -3
  max_rot_vel: 3
  min_rot_vel: 0
  min_in_place_vel_theta: 0
  escape_vel: -0.2

  acc_lim_theta: 20
  acc_lim_x: 3
  acc_lim_y: 0

  holonomic_robot: false
  meter_scoring: true
  # gdist_scale: 4.0
  # occdist_scale: 1.0
  goal_distance_bias: 2
  path_distance_bias: 80


  xy_goal_tolerance: 0.02
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false
  clearing_rotation_allowed: false

  sim_time: 2
  sim_period: 0.02
  sim_granularity: 0.01
  angular_sim_granularity: 0.01
  vx_samples: 30
  vth_samples: 30
  vy_samples: 0
  

