footprint: [[-0.11,-0.11],[-0.11,0.11], [0.11, 0.11], [0.11,-0.11]] 

obstacle_layer:
  obstacle_range: 12
  raytrace_range: 14
  map_type: costmap
  
  observation_sources: lidar
  lidar: {sensor_frame: top_rplidar_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

inflation_layer:
  cost_scaling_factor: 5