footprint: [[-0.2,-0.2],[-0.2,0.2], [0.2, 0.2], [0.2,-0.2]] 

obstacle_layer:
  obstacle_range: 6
  raytrace_range: 12
  map_type: costmap
  
  observation_sources: scan #point_cloud_sensor
  scan: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

inflation_layer:
  inflation_radius: 0.75
  cost_scaling_factor: 5.0