local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 3.0
  publish_frequency: 3.0
  static_map: false
  rolling_window: true
  width: 4
  height: 4
  resolution: 0.025
  inflation_layer:
    inflation_radius: 0.15

  plugins:
  - {name: static_layer,    type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}