rhodent:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60  
  right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_wheel_joint
    pid: {p: 0.3, i: 2, d: 0.0}
  left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_wheel_joint
    pid: {p: 0.3, i: 2, d: 0.0}