rhodent:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60  
  right_wheel_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: right_wheel_joint
    # pid: {p: 5.0, i: 0.0, d: 0.0}
  left_wheel_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: left_wheel_joint
    # pid: {p: 5.0, i: 0.0, d: 0.0}